### ISSUE TITLE
delay to apply effect

### ISSUE THREAD

**Issue by saeid-pm** [mirrajabi/ViewEffects#4]
i used  ViewFilter.getInstance(this)..... code in onCreate() method but "blur effect" apply about 2-4 second after the app is loaded

**Comment by mirrajabi** [comment]
@saeid-pm, It may be a problem with the algorithm.
I used _fast blur_ algorithm adapted from here [https://stackoverflow.com/a/10028267/5626646](https://stackoverflow.com/a/10028267/5626646) which is originally based on this one [http://www.quasimondo.com/StackBlurForCanvas/StackBlur.js](http://www.quasimondo.com/StackBlurForCanvas/StackBlur.js).

The library is supposed to give you the full control over the effect you're applying. You can use another algorithm by implementing an instance of [IRendered](https://github.com/mirrajabi/view-effects/blob/master/library/src/main/java/ir/mirrajabi/viewfilter/core/IRenderer.java) and you can also contribute your custom renderers to improve this lib.
